# Generated by Django 4.0.1 on 2022-05-12 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('product_quantity', models.IntegerField()),
                ('creat_date', models.DateTimeField(auto_now_add=True)),
                ('exp_date', models.DateField()),
            ],
            options={
                'db_table': 'prods',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.products')),
            ],
        ),
    ]
