# Generated by Django 4.0.1 on 2022-05-12 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orders',
            table='order',
        ),
    ]
